### PR TITLE
feat: improve information panel

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
closes : https://github.com/zakodium-oss/pixelium/issues/55

### CODE REVIEW

**Comment by stropitek** [comment]
@wadjih-bencheikh18 can you push something so that we can a preview?

**Comment by wadjih-bencheikh18** [comment]
> we get a preview?

The preview is ready

**Review by lpatiny — APPROVED** [review]
functionality is ok

**Review by stropitek — APPROVED** [review]

**Comment by stropitek** [comment]
@wadjih-bencheikh18 there is a conflict

**Comment by stropitek** [comment]
Since `package.json` has not changed with respect to `main`, I don't think there should be changes in the `package-lock.json`. During the merge you should have kept the `package-lock.json` as it is on `main`

**Comment by Xstoudi** [comment]
The changes in `package-lock.json` are probably justified because the project use [react-swc](https://swc.rs/) which is a native module.

**Pull request merged**
